# Generated by Django 3.1.7 on 2021-03-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraEntrada', models.DateTimeField()),
                ('fechaHoraSalida', models.DateTimeField()),
                ('costoTotal', models.IntegerField()),
                ('obsevacion', models.TextField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.estado')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
                ('registrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.registrador')),
            ],
        ),
    ]
